name: wobei
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  path_provider: ^1.6.9 #路径获取
  provider: ^3.0.0+1 #跨组件数据共享
  http: ^0.12.1 #网络请求
  dio: ^3.0.9 #网络请求
  crypto: ^2.1.3 #加密
  package_info: ^0.4.0+2 #获取包信息 https://www.jianshu.com/p/1a2fe3937499
  device_info: ^0.4.0+1 #获取设备信息 https://www.jianshu.com/p/4b6ac2014cb2
  shared_preferences: ^0.5.7 #本地存储
  fluttertoast: ^3.1.0 #toast工具类
  flutter_native_splash: ^0.1.9 #启动页
  flutter_swiper: ^1.1.6 #轮播图
  date_format: ^1.0.8 #时间格式化
  english_words: ^3.1.5 #生成随机单词
  flashy_tab_bar: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: money
      fonts:
        - asset: assets/fonts/money.ttf

  assets:
    - assets/images/welcome.png
    - assets/images/2.0x/welcome.png
    - assets/images/3.0x/welcome.png
    - assets/images/home_active.png
    - assets/images/2.0x/home_active.png
    - assets/images/3.0x/home_active.png
    - assets/images/home_normal.png
    - assets/images/2.0x/home_normal.png
    - assets/images/3.0x/home_normal.png
    - assets/images/right_active.png
    - assets/images/2.0x/right_active.png
    - assets/images/3.0x/right_active.png
    - assets/images/right_normal.png
    - assets/images/2.0x/right_normal.png
    - assets/images/3.0x/right_normal.png
    - assets/images/myself_active.png
    - assets/images/2.0x/myself_active.png
    - assets/images/3.0x/myself_active.png
    - assets/images/search.png
    - assets/images/2.0x/search.png
    - assets/images/3.0x/search.png
    - assets/images/myself_normal.png
    - assets/images/2.0x/myself_normal.png
    - assets/images/3.0x/myself_normal.png
    - assets/images/location_l.png
    - assets/images/2.0x/location_l.png
    - assets/images/3.0x/location_l.png
    - assets/images/mall.png
    - assets/images/2.0x/mall.png
    - assets/images/3.0x/mall.png
    - assets/images/recharge.png
    - assets/images/2.0x/recharge.png
    - assets/images/3.0x/recharge.png
    - assets/images/exclusive.png
    - assets/images/2.0x/exclusive.png
    - assets/images/3.0x/exclusive.png
    - assets/images/back_black.png
    - assets/images/2.0x/back_black.png
    - assets/images/3.0x/back_black.png
    - assets/images/hecard_price.png
    - assets/images/2.0x/hecard_price.png
    - assets/images/3.0x/hecard_price.png
    - assets/images/close.png
    - assets/images/2.0x/close.png
    - assets/images/3.0x/close.png


    # To add assets to your application, add an assets section, like this:
    # assets:
    #  -  assets/images/a_dot_burr.jpeg
    #  -  assets/images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:

  #     - family: Schyler
  #       fonts:
  #         - asset: fonts/Schyler-Regular.ttf
  #         - asset: fonts/Schyler-Italic.ttf
  #           style: italic
  #     - family: Trajan Pro
  #       fonts:
  #         - asset: fonts/TrajanPro.ttf
  #         - asset: fonts/TrajanPro_Bold.ttf
  #           weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

#flutter_native_splash:
#  image: images/welcome.png
#  fill: true
#  color: "42a5f5"
